INSERT INTO "public"."g2p_register_schemas" ("register_id","deduplicate_schema","search_result_schema","filter_schema") VALUES
-- Individual
('a0000000-0000-4000-8000-000000000001',
 '[{"field_name": "first_name", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "last_name", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "birth_date", "match_type": "exact", "weight": 0.2}, {"field_name": "foundational_id", "match_type": "exact", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Individual ID", "order": 1}, {"field_name": "first_name", "display_label": "First Name", "order": 2}, {"field_name": "last_name", "display_label": "Last Name", "order": 3}, {"field_name": "gender", "display_label": "Gender", "order": 4}, {"field_name": "birth_date", "display_label": "Birth Date", "order": 5}, {"field_name": "disability_status", "display_label": "Disability", "order": 6}, {"field_name": "displacement_status", "display_label": "Displacement", "order": 7}]',
 '[{"field_name": "first_name", "display_label": "First Name", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "last_name", "display_label": "Last Name", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}, {"field_name": "gender", "display_label": "Gender", "filter_type": "dropdown", "order": 3, "allowed_operators": ["eq", "in"], "options_source": [{"value": "MALE", "label": "MALE"}, {"value": "FEMALE", "label": "FEMALE"}, {"value": "OTHERS", "label": "OTHERS"}, {"value": "UNKNOWN", "label": "UNKNOWN"}]}, {"field_name": "birth_date", "display_label": "Birthdate", "filter_type": "date_range", "order": 4, "allowed_operators": ["eq", "gt", "gte", "lt", "lte", "between"]}, {"field_name": "disability_status", "display_label": "Disability Status", "filter_type": "dropdown", "order": 5, "allowed_operators": ["eq"], "options_source": [{"value": "YES", "label": "YES"}, {"value": "NO", "label": "NO"}, {"value": "UNKNOWN", "label": "UNKNOWN"}]}, {"field_name": "displacement_status", "display_label": "Displacement Status", "filter_type": "dropdown", "order": 6, "allowed_operators": ["eq", "in"], "options_source": [{"value": "HOST_COMMUNITY", "label": "HOST_COMMUNITY"}, {"value": "IDP", "label": "IDP"}, {"value": "RETURNEE", "label": "RETURNEE"}, {"value": "REFUGEE", "label": "REFUGEE"}]}, {"field_name": "record_status", "display_label": "Record Status", "filter_type": "dropdown", "order": 7, "allowed_operators": ["eq", "in"], "options_source": [{"value": "ACTIVE", "label": "ACTIVE"}, {"value": "INACTIVE", "label": "INACTIVE"}, {"value": "ARCHIVED", "label": "ARCHIVED"}]}]'),

-- Household
('a0000000-0000-4000-8000-000000000002',
 '[{"field_name": "household_head_name", "match_type": "fuzzy", "weight": 0.5}, {"field_name": "address_line_1", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "size_total", "match_type": "exact", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Household ID", "order": 1}, {"field_name": "household_head_name", "display_label": "Head", "order": 2}, {"field_name": "headship_type", "display_label": "Headship", "order": 3}, {"field_name": "size_total", "display_label": "Size", "order": 4}, {"field_name": "dwelling_type", "display_label": "Dwelling", "order": 5}, {"field_name": "address_line_1", "display_label": "Address", "order": 6}]',
 '[{"field_name": "household_head_name", "display_label": "Head", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "headship_type", "display_label": "Headship", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "MALE_HEADED", "label": "MALE_HEADED"}, {"value": "FEMALE_HEADED", "label": "FEMALE_HEADED"}, {"value": "CHILD_HEADED", "label": "CHILD_HEADED"}, {"value": "ELDERLY_HEADED", "label": "ELDERLY_HEADED"}, {"value": "DISABLED_HEADED", "label": "DISABLED_HEADED"}]}, {"field_name": "size_total", "display_label": "Total Size", "filter_type": "number", "order": 3, "allowed_operators": ["eq", "gt", "gte", "lt", "lte"]}, {"field_name": "dwelling_type", "display_label": "Dwelling", "filter_type": "dropdown", "order": 4, "allowed_operators": ["eq", "in"], "options_source": [{"value": "PERMANENT", "label": "PERMANENT"}, {"value": "SEMI_PERMANENT", "label": "SEMI_PERMANENT"}, {"value": "TEMPORARY", "label": "TEMPORARY"}]}]'),

-- ProgramParticipation
('b0000000-0000-4000-8000-000000000010',
 '[{"field_name": "program_name", "match_type": "fuzzy", "weight": 0.5}, {"field_name": "program_mnemonic", "match_type": "exact", "weight": 0.3}, {"field_name": "legacy_program_id", "match_type": "exact", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Participation ID", "order": 1}, {"field_name": "program_name", "display_label": "Programme", "order": 2}, {"field_name": "program_start_date", "display_label": "Start", "order": 3}, {"field_name": "program_exit_date", "display_label": "Exit", "order": 4}, {"field_name": "payment_channel_preference", "display_label": "Payment Channel", "order": 5}]',
 '[{"field_name": "program_name", "display_label": "Programme", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "payment_channel_preference", "display_label": "Payment Channel", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}]'),

-- PovertyScore
('b0000000-0000-4000-8000-000000000020',
 '[{"field_name": "pmt_score", "match_type": "exact", "weight": 0.7}, {"field_name": "pmt_score_type", "match_type": "fuzzy", "weight": 0.3}]',
 '[{"field_name": "functional_record_id", "display_label": "Score ID", "order": 1}, {"field_name": "pmt_score", "display_label": "Score", "order": 2}, {"field_name": "pmt_score_type", "display_label": "Type", "order": 3}, {"field_name": "pmt_calculation_date", "display_label": "Calculated", "order": 4}]',
 '[{"field_name": "pmt_score", "display_label": "Score", "filter_type": "number", "order": 1, "allowed_operators": ["eq", "gt", "lt", "between"]}, {"field_name": "pmt_score_type", "display_label": "Score Type", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "PMT", "label": "PMT"}, {"value": "MPI", "label": "MPI"}, {"value": "PPI", "label": "PPI"}, {"value": "CUSTOM", "label": "CUSTOM"}]}]'),

-- Asset
('b0000000-0000-4000-8000-000000000030',
 '[{"field_name": "asset_type", "match_type": "exact", "weight": 0.4}, {"field_name": "asset_category", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "quantity", "match_type": "exact", "weight": 0.3}]',
 '[{"field_name": "functional_record_id", "display_label": "Asset ID", "order": 1}, {"field_name": "asset_type", "display_label": "Type", "order": 2}, {"field_name": "asset_category", "display_label": "Category", "order": 3}, {"field_name": "quantity", "display_label": "Quantity", "order": 4}, {"field_name": "size_band", "display_label": "Size Band", "order": 5}]',
 '[{"field_name": "asset_type", "display_label": "Type", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "LAND", "label": "LAND"}, {"value": "LIVESTOCK", "label": "LIVESTOCK"}, {"value": "PRODUCTIVE_TOOL", "label": "PRODUCTIVE_TOOL"}, {"value": "CONSUMER_DURABLE", "label": "CONSUMER_DURABLE"}, {"value": "VEHICLE", "label": "VEHICLE"}, {"value": "OTHER", "label": "OTHER"}]}, {"field_name": "quantity", "display_label": "Quantity", "filter_type": "number", "order": 2, "allowed_operators": ["eq", "gt", "lt"]}]'),

-- Shock
('b0000000-0000-4000-8000-000000000040',
 '[{"field_name": "shock_type", "match_type": "exact", "weight": 0.5}, {"field_name": "shock_period", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "coping_strategy", "match_type": "fuzzy", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Shock ID", "order": 1}, {"field_name": "shock_type", "display_label": "Shock", "order": 2}, {"field_name": "shock_period", "display_label": "Period", "order": 3}, {"field_name": "coping_strategy", "display_label": "Coping Strategy", "order": 4}]',
 '[{"field_name": "shock_type", "display_label": "Shock Type", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "shock_period", "display_label": "Period", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}]'),

-- Consent
('b0000000-0000-4000-8000-000000000050',
 '[{"field_name": "consent_captured", "match_type": "exact", "weight": 0.5}, {"field_name": "consent_method", "match_type": "exact", "weight": 0.5}]',
 '[{"field_name": "functional_record_id", "display_label": "Consent ID", "order": 1}, {"field_name": "consent_captured", "display_label": "Captured", "order": 2}, {"field_name": "consent_method", "display_label": "Method", "order": 3}, {"field_name": "consent_date", "display_label": "Date", "order": 4}]',
 '[{"field_name": "consent_captured", "display_label": "Captured", "filter_type": "boolean", "order": 1, "allowed_operators": ["eq"]}, {"field_name": "consent_method", "display_label": "Method", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "SIGNED", "label": "SIGNED"}, {"value": "VERBAL", "label": "VERBAL"}, {"value": "DIGITAL", "label": "DIGITAL"}, {"value": "BIOMETRIC", "label": "BIOMETRIC"}]}]'),

-- Grievance
('b0000000-0000-4000-8000-000000000060',
 '[{"field_name": "grievance_case_id", "match_type": "exact", "weight": 0.6}, {"field_name": "grievance_type", "match_type": "exact", "weight": 0.4}]',
 '[{"field_name": "functional_record_id", "display_label": "Grievance ID", "order": 1}, {"field_name": "grievance_case_id", "display_label": "Case ID", "order": 2}, {"field_name": "grievance_type", "display_label": "Type", "order": 3}, {"field_name": "grievance_status", "display_label": "Status", "order": 4}, {"field_name": "submission_date", "display_label": "Submitted", "order": 5}]',
 '[{"field_name": "grievance_type", "display_label": "Type", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "EXCLUSION", "label": "EXCLUSION"}, {"value": "INCLUSION", "label": "INCLUSION"}, {"value": "DATA_ERROR", "label": "DATA_ERROR"}, {"value": "PAYMENT", "label": "PAYMENT"}, {"value": "PROTECTION", "label": "PROTECTION"}, {"value": "OTHER", "label": "OTHER"}]}, {"field_name": "grievance_status", "display_label": "Status", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "OPEN", "label": "OPEN"}, {"value": "UNDER_REVIEW", "label": "UNDER_REVIEW"}, {"value": "RESOLVED", "label": "RESOLVED"}, {"value": "APPEALED", "label": "APPEALED"}, {"value": "CLOSED", "label": "CLOSED"}]}]'),

-- VerificationHistory
('b0000000-0000-4000-8000-000000000070',
 '[{"field_name": "update_trigger", "match_type": "exact", "weight": 0.3}, {"field_name": "verification_method", "match_type": "exact", "weight": 0.3}, {"field_name": "enumerator_id", "match_type": "exact", "weight": 0.4}]',
 '[{"field_name": "functional_record_id", "display_label": "Verification ID", "order": 1}, {"field_name": "update_trigger", "display_label": "Trigger", "order": 2}, {"field_name": "verification_method", "display_label": "Method", "order": 3}, {"field_name": "verification_status", "display_label": "Status", "order": 4}, {"field_name": "verified_at", "display_label": "Verified At", "order": 5}]',
 '[{"field_name": "verification_status", "display_label": "Verification Status", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "UNVERIFIED", "label": "UNVERIFIED"}, {"value": "VERIFIED", "label": "VERIFIED"}, {"value": "SPOT_CHECKED", "label": "SPOT_CHECKED"}]}, {"field_name": "update_trigger", "display_label": "Trigger", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "ON_DEMAND", "label": "ON_DEMAND"}, {"value": "RECERTIFICATION", "label": "RECERTIFICATION"}, {"value": "LIFE_EVENT", "label": "LIFE_EVENT"}, {"value": "SHOCK", "label": "SHOCK"}, {"value": "INTEGRATION_SYNC", "label": "INTEGRATION_SYNC"}]}]');
