INSERT INTO "public"."g2p_register_schemas" ("register_id","deduplicate_schema","search_result_schema","filter_schema") VALUES
-- Individual
-- Search-result fields are ordered for at-a-glance recognition of an
-- individual: ID first, then full name (most readable), then masked
-- foundational ID (audit/verification anchor), then person-level
-- demographics (gender, DOB, marital status), then citizenship and a
-- locality clue (address line 1) so officers can disambiguate quickly.
('a0000000-0000-4000-8000-000000000001',
 '[{"field_name": "first_name", "match_type": "fuzzy", "weight": 0.25}, {"field_name": "last_name", "match_type": "fuzzy", "weight": 0.25}, {"field_name": "birth_date", "match_type": "exact", "weight": 0.2}, {"field_name": "foundational_id", "match_type": "exact", "weight": 0.3}]',
 '[{"field_name": "functional_record_id", "display_label": "Individual ID", "order": 1}, {"field_name": "full_name", "display_label": "Full Name", "order": 2}, {"field_name": "foundational_id_masked", "display_label": "Foundational ID", "order": 3}, {"field_name": "gender", "display_label": "Gender", "order": 4}, {"field_name": "birth_date", "display_label": "Birth Date", "order": 5}, {"field_name": "marital_status", "display_label": "Marital Status", "order": 6}, {"field_name": "citizenship_category", "display_label": "Citizenship", "order": 7}, {"field_name": "address_line_1", "display_label": "Address", "order": 8}]',
 '[{"field_name": "full_name", "display_label": "Full Name", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "first_name", "display_label": "First Name", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}, {"field_name": "last_name", "display_label": "Last Name", "filter_type": "text", "order": 3, "allowed_operators": ["eq", "contains"]}, {"field_name": "gender", "display_label": "Gender", "filter_type": "dropdown", "order": 4, "allowed_operators": ["eq", "in"], "options_source": [{"value": "MALE", "label": "MALE"}, {"value": "FEMALE", "label": "FEMALE"}, {"value": "OTHERS", "label": "OTHERS"}, {"value": "UNKNOWN", "label": "UNKNOWN"}]}, {"field_name": "birth_date", "display_label": "Birthdate", "filter_type": "date_range", "order": 5, "allowed_operators": ["eq", "gt", "gte", "lt", "lte", "between"]}, {"field_name": "marital_status", "display_label": "Marital Status", "filter_type": "dropdown", "order": 6, "allowed_operators": ["eq", "in"], "options_source": [{"value": "SINGLE", "label": "SINGLE"}, {"value": "MARRIED", "label": "MARRIED"}, {"value": "DIVORCED", "label": "DIVORCED"}, {"value": "WIDOWED", "label": "WIDOWED"}, {"value": "SEPARATED", "label": "SEPARATED"}, {"value": "UNKNOWN", "label": "UNKNOWN"}]}, {"field_name": "citizenship_category", "display_label": "Citizenship", "filter_type": "dropdown", "order": 7, "allowed_operators": ["eq", "in"], "options_source": [{"value": "CITIZEN", "label": "CITIZEN"}, {"value": "REFUGEE", "label": "REFUGEE"}, {"value": "IDP", "label": "IDP"}, {"value": "RETURNEE", "label": "RETURNEE"}, {"value": "RESIDENT", "label": "RESIDENT"}]}, {"field_name": "disability_status", "display_label": "Disability", "filter_type": "dropdown", "order": 8, "allowed_operators": ["eq"], "options_source": [{"value": "YES", "label": "YES"}, {"value": "NO", "label": "NO"}, {"value": "UNKNOWN", "label": "UNKNOWN"}]}, {"field_name": "record_status", "display_label": "Record Status", "filter_type": "dropdown", "order": 9, "allowed_operators": ["eq", "in"], "options_source": [{"value": "ACTIVE", "label": "ACTIVE"}, {"value": "INACTIVE", "label": "INACTIVE"}, {"value": "ARCHIVED", "label": "ARCHIVED"}]}]'),

-- Household
-- Search-result fields: ID, head, household composition (size + headship type),
-- then dwelling and a locality clue. No country-specific admin-hierarchy
-- columns (region/woreda/kebele) — generic G2PGeo `address_line_1` is used.
('a0000000-0000-4000-8000-000000000002',
 '[{"field_name": "household_head_name", "match_type": "fuzzy", "weight": 0.5}, {"field_name": "address_line_1", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "size_total", "match_type": "exact", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Household ID", "order": 1}, {"field_name": "household_head_name", "display_label": "Head", "order": 2}, {"field_name": "headship_type", "display_label": "Headship", "order": 3}, {"field_name": "size_total", "display_label": "Members", "order": 4}, {"field_name": "dwelling_type", "display_label": "Dwelling", "order": 5}, {"field_name": "tenure_status", "display_label": "Tenure", "order": 6}, {"field_name": "address_line_1", "display_label": "Address", "order": 7}]',
 '[{"field_name": "household_head_name", "display_label": "Head", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "headship_type", "display_label": "Headship", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "MALE_HEADED", "label": "MALE_HEADED"}, {"value": "FEMALE_HEADED", "label": "FEMALE_HEADED"}, {"value": "CHILD_HEADED", "label": "CHILD_HEADED"}, {"value": "ELDERLY_HEADED", "label": "ELDERLY_HEADED"}, {"value": "DISABLED_HEADED", "label": "DISABLED_HEADED"}]}, {"field_name": "size_total", "display_label": "Total Size", "filter_type": "number", "order": 3, "allowed_operators": ["eq", "gt", "gte", "lt", "lte"]}, {"field_name": "dwelling_type", "display_label": "Dwelling", "filter_type": "dropdown", "order": 4, "allowed_operators": ["eq", "in"], "options_source": [{"value": "PERMANENT", "label": "PERMANENT"}, {"value": "SEMI_PERMANENT", "label": "SEMI_PERMANENT"}, {"value": "TEMPORARY", "label": "TEMPORARY"}]}, {"field_name": "tenure_status", "display_label": "Tenure", "filter_type": "dropdown", "order": 5, "allowed_operators": ["eq", "in"], "options_source": [{"value": "OWNED", "label": "OWNED"}, {"value": "RENTED", "label": "RENTED"}, {"value": "HOSTED", "label": "HOSTED"}, {"value": "TEMPORARY", "label": "TEMPORARY"}]}, {"field_name": "address_line_1", "display_label": "Address", "filter_type": "text", "order": 6, "allowed_operators": ["eq", "contains"]}]'),

-- IndividualProgram
('b0000000-0000-4000-8000-000000000010',
 '[{"field_name": "program_name", "match_type": "fuzzy", "weight": 0.5}, {"field_name": "program_mnemonic", "match_type": "exact", "weight": 0.3}, {"field_name": "legacy_program_id", "match_type": "exact", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Individual Programme ID", "order": 1}, {"field_name": "program_name", "display_label": "Programme", "order": 2}, {"field_name": "program_start_date", "display_label": "Start", "order": 3}, {"field_name": "program_exit_date", "display_label": "Exit", "order": 4}, {"field_name": "payment_channel_preference", "display_label": "Payment Channel", "order": 5}]',
 '[{"field_name": "program_name", "display_label": "Programme", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "payment_channel_preference", "display_label": "Payment Channel", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}]'),

-- HouseholdProgram
('b0000000-0000-4000-8000-000000000090',
 '[{"field_name": "program_name", "match_type": "fuzzy", "weight": 0.5}, {"field_name": "program_mnemonic", "match_type": "exact", "weight": 0.3}, {"field_name": "legacy_program_id", "match_type": "exact", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Household Programme ID", "order": 1}, {"field_name": "program_name", "display_label": "Programme", "order": 2}, {"field_name": "program_start_date", "display_label": "Start", "order": 3}, {"field_name": "program_exit_date", "display_label": "Exit", "order": 4}, {"field_name": "payment_channel_preference", "display_label": "Payment Channel", "order": 5}]',
 '[{"field_name": "program_name", "display_label": "Programme", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "payment_channel_preference", "display_label": "Payment Channel", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}]'),

-- HouseholdAsset
('b0000000-0000-4000-8000-000000000030',
 '[{"field_name": "asset_type", "match_type": "exact", "weight": 0.4}, {"field_name": "asset_category", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "quantity", "match_type": "exact", "weight": 0.3}]',
 '[{"field_name": "functional_record_id", "display_label": "Household Asset ID", "order": 1}, {"field_name": "asset_type", "display_label": "Type", "order": 2}, {"field_name": "asset_category", "display_label": "Category", "order": 3}, {"field_name": "quantity", "display_label": "Quantity", "order": 4}, {"field_name": "size_band", "display_label": "Size Band", "order": 5}]',
 '[{"field_name": "asset_type", "display_label": "Type", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "LAND", "label": "LAND"}, {"value": "LIVESTOCK", "label": "LIVESTOCK"}, {"value": "PRODUCTIVE_TOOL", "label": "PRODUCTIVE_TOOL"}, {"value": "CONSUMER_DURABLE", "label": "CONSUMER_DURABLE"}, {"value": "VEHICLE", "label": "VEHICLE"}, {"value": "OTHER", "label": "OTHER"}]}, {"field_name": "quantity", "display_label": "Quantity", "filter_type": "number", "order": 2, "allowed_operators": ["eq", "gt", "lt"]}]'),

-- IndividualShock
('b0000000-0000-4000-8000-000000000040',
 '[{"field_name": "shock_type", "match_type": "exact", "weight": 0.5}, {"field_name": "shock_period", "match_type": "fuzzy", "weight": 0.3}, {"field_name": "coping_strategy", "match_type": "fuzzy", "weight": 0.2}]',
 '[{"field_name": "functional_record_id", "display_label": "Individual Shock ID", "order": 1}, {"field_name": "shock_type", "display_label": "Shock", "order": 2}, {"field_name": "shock_period", "display_label": "Period", "order": 3}, {"field_name": "coping_strategy", "display_label": "Coping Strategy", "order": 4}]',
 '[{"field_name": "shock_type", "display_label": "Shock Type", "filter_type": "text", "order": 1, "allowed_operators": ["eq", "contains"]}, {"field_name": "shock_period", "display_label": "Period", "filter_type": "text", "order": 2, "allowed_operators": ["eq", "contains"]}]'),

-- IndividualDisability
('b0000000-0000-4000-8000-000000000080',
 '[{"field_name": "disability_domain", "match_type": "exact", "weight": 0.6}, {"field_name": "disability_severity", "match_type": "exact", "weight": 0.4}]',
 '[{"field_name": "functional_record_id", "display_label": "Disability ID", "order": 1}, {"field_name": "disability_domain", "display_label": "Domain", "order": 2}, {"field_name": "disability_severity", "display_label": "Severity", "order": 3}]',
 '[{"field_name": "disability_domain", "display_label": "Domain", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "VISION", "label": "VISION"}, {"value": "HEARING", "label": "HEARING"}, {"value": "MOBILITY", "label": "MOBILITY"}, {"value": "COGNITION", "label": "COGNITION"}, {"value": "SELF_CARE", "label": "SELF_CARE"}, {"value": "COMMUNICATION", "label": "COMMUNICATION"}]}, {"field_name": "disability_severity", "display_label": "Severity", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "NO_DIFFICULTY", "label": "NO_DIFFICULTY"}, {"value": "SOME_DIFFICULTY", "label": "SOME_DIFFICULTY"}, {"value": "A_LOT_OF_DIFFICULTY", "label": "A_LOT_OF_DIFFICULTY"}, {"value": "CANNOT_DO_AT_ALL", "label": "CANNOT_DO_AT_ALL"}]}]'),

-- HouseholdHousingAndServices
('b0000000-0000-4000-8000-000000000011',
 '[{"field_name": "dwelling_type", "match_type": "exact", "weight": 0.25}, {"field_name": "water_source_type", "match_type": "exact", "weight": 0.25}, {"field_name": "roof_material", "match_type": "exact", "weight": 0.25}, {"field_name": "cooking_fuel_type", "match_type": "exact", "weight": 0.25}]',
 '[{"field_name": "functional_record_id", "display_label": "Housing & Services ID", "order": 1}, {"field_name": "dwelling_type", "display_label": "Dwelling", "order": 2}, {"field_name": "roof_material", "display_label": "Roof", "order": 3}, {"field_name": "water_source_type", "display_label": "Water", "order": 4}, {"field_name": "sanitation_type", "display_label": "Sanitation", "order": 5}, {"field_name": "cooking_fuel_type", "display_label": "Cooking Fuel", "order": 6}]',
 '[{"field_name": "dwelling_type", "display_label": "Dwelling", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "PERMANENT", "label": "PERMANENT"}, {"value": "SEMI_PERMANENT", "label": "SEMI_PERMANENT"}, {"value": "TEMPORARY", "label": "TEMPORARY"}]}, {"field_name": "water_source_type", "display_label": "Water", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "PIPED", "label": "PIPED"}, {"value": "PUBLIC_TAP", "label": "PUBLIC_TAP"}, {"value": "WELL", "label": "WELL"}, {"value": "SPRING", "label": "SPRING"}, {"value": "SURFACE_WATER", "label": "SURFACE_WATER"}, {"value": "RAINWATER", "label": "RAINWATER"}, {"value": "TANKER_TRUCK", "label": "TANKER_TRUCK"}, {"value": "OTHER", "label": "OTHER"}]}]'),

-- IndividualLand
('b0000000-0000-4000-8000-000000000012',
 '[{"field_name": "land_access", "match_type": "exact", "weight": 0.5}, {"field_name": "land_size", "match_type": "exact", "weight": 0.5}]',
 '[{"field_name": "functional_record_id", "display_label": "Land Record ID", "order": 1}, {"field_name": "land_access", "display_label": "Land Access", "order": 2}, {"field_name": "land_size", "display_label": "Land Size", "order": 3}]',
 '[{"field_name": "land_access", "display_label": "Land Access", "filter_type": "text", "order": 1, "allowed_operators": ["eq"]}]'),

-- IndividualLivelihood
('b0000000-0000-4000-8000-000000000013',
 '[{"field_name": "primary_livelihood", "match_type": "exact", "weight": 0.5}, {"field_name": "employment_status", "match_type": "exact", "weight": 0.5}]',
 '[{"field_name": "functional_record_id", "display_label": "Livelihood Record ID", "order": 1}, {"field_name": "primary_livelihood", "display_label": "Primary Livelihood", "order": 2}, {"field_name": "secondary_livelihood", "display_label": "Secondary Livelihood", "order": 3}, {"field_name": "employment_status", "display_label": "Employment", "order": 4}]',
 '[{"field_name": "primary_livelihood", "display_label": "Primary Livelihood", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "AGRICULTURE", "label": "AGRICULTURE"}, {"value": "LIVESTOCK", "label": "LIVESTOCK"}, {"value": "FISHING", "label": "FISHING"}, {"value": "WAGE_LABOR", "label": "WAGE_LABOR"}, {"value": "SELF_EMPLOYMENT", "label": "SELF_EMPLOYMENT"}, {"value": "GOVERNMENT_EMPLOYEE", "label": "GOVERNMENT_EMPLOYEE"}, {"value": "PRIVATE_SECTOR_EMPLOYEE", "label": "PRIVATE_SECTOR_EMPLOYEE"}, {"value": "BUSINESS_TRADE", "label": "BUSINESS_TRADE"}, {"value": "REMITTANCE", "label": "REMITTANCE"}, {"value": "PENSION", "label": "PENSION"}, {"value": "UNEMPLOYED", "label": "UNEMPLOYED"}, {"value": "OTHER", "label": "OTHER"}]}]'),

-- IndividualLivestock
('b0000000-0000-4000-8000-000000000014',
 '[{"field_name": "livestock_species", "match_type": "exact", "weight": 0.6}, {"field_name": "livestock_counts", "match_type": "exact", "weight": 0.4}]',
 '[{"field_name": "functional_record_id", "display_label": "Livestock Record ID", "order": 1}, {"field_name": "livestock_species", "display_label": "Species", "order": 2}, {"field_name": "livestock_counts", "display_label": "Count Band", "order": 3}]',
 '[{"field_name": "livestock_species", "display_label": "Species", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq", "in"], "options_source": [{"value": "CATTLE", "label": "CATTLE"}, {"value": "GOATS", "label": "GOATS"}, {"value": "SHEEP", "label": "SHEEP"}, {"value": "POULTRY", "label": "POULTRY"}, {"value": "CAMELS", "label": "CAMELS"}, {"value": "EQUINES", "label": "EQUINES"}, {"value": "OTHER", "label": "OTHER"}]}]'),

-- IndividualVulnerability
('b0000000-0000-4000-8000-000000000015',
 '[{"field_name": "disability_status", "match_type": "exact", "weight": 0.34}, {"field_name": "displacement_status", "match_type": "exact", "weight": 0.33}, {"field_name": "pastoralist_classification", "match_type": "exact", "weight": 0.33}]',
 '[{"field_name": "functional_record_id", "display_label": "Vulnerability Record ID", "order": 1}, {"field_name": "disability_status", "display_label": "Disability Status", "order": 2}, {"field_name": "displacement_status", "display_label": "Displacement", "order": 3}, {"field_name": "pastoralist_classification", "display_label": "Pastoralist", "order": 4}]',
 '[{"field_name": "disability_status", "display_label": "Disability Status", "filter_type": "dropdown", "order": 1, "allowed_operators": ["eq"], "options_source": [{"value": "YES", "label": "YES"}, {"value": "NO", "label": "NO"}, {"value": "UNKNOWN", "label": "UNKNOWN"}]}, {"field_name": "displacement_status", "display_label": "Displacement", "filter_type": "dropdown", "order": 2, "allowed_operators": ["eq", "in"], "options_source": [{"value": "HOST_COMMUNITY", "label": "HOST_COMMUNITY"}, {"value": "IDP", "label": "IDP"}, {"value": "RETURNEE", "label": "RETURNEE"}, {"value": "REFUGEE", "label": "REFUGEE"}]}]');
