from .g2p_register_domain_service_individual import G2PRegisterDomainServiceIndividual
from .g2p_register_domain_service_individual_disability import (
    G2PRegisterDomainServiceIndividualDisability,
)
from .g2p_register_domain_service_household import G2PRegisterDomainServiceHousehold
from .g2p_register_domain_service_program_participation import (
    G2PRegisterDomainServiceProgramParticipation,
)
from .g2p_register_domain_service_poverty_score import G2PRegisterDomainServicePovertyScore
from .g2p_register_domain_service_asset import G2PRegisterDomainServiceAsset
from .g2p_register_domain_service_shock import G2PRegisterDomainServiceShock
from .g2p_register_domain_service_consent import G2PRegisterDomainServiceConsent
from .g2p_register_domain_service_grievance import G2PRegisterDomainServiceGrievance
